### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by dracoqcca** [sktaylortrash/TCPLightingWebInterface-MQTT#5]
Hi Paul,

I have a question for you. I'm wondering if it could be possible to add a new feature. I have RF remotes with my system and I only have 2 button use on it. It could be great if we could have virtual device that could be bind to some entities in home assistant. So I could turn on/off other light in my home with that remote.

**Comment by sktaylortrash** [comment]
So I'm not totally sure what you're asking for.  I currently use a bunch of Zigbee remotes to turn my TCPi  lights off and on by using HA automations. 
Can Home Assistant see the remotes already? like with an RF bridge of some sort?  If so then you should be able to attach the button events to actions in HA

**Comment by Dracoqc** [comment]
Hi Paul,

Sorry if i’m not clear. I’m using this remote 

https://m.smarthomedb.com/files/product/tcp-connected-remote_1.jpg
To turn on/off my light bulb. It’s setup in the bridge you link it the same way as you link the bulb. Then you can link one of the 4 button to a light in the bridge. So I was wondering if I could use that to triger an automation that will turn on for example a sonoff light using the webinterface.

**Comment by sktaylortrash** [comment]
Oh those remotes were super limited. No matter how many you added to the bridge you could only link the 4 buttons to the same thing. So button 1 on every remote controlled the same bulb. 

From the documentation it seemed like they were really only for controlling bulbs that weren't added to a hub. When used with the hub it seems like it still pairs the remote directly with the bulb.

I can't think of any way to catch the button event and send it out.

**Comment by dracoqcca** [comment]
Ok thank you.

**Comment by dracoqcca** [comment]
last question for you do you know any brand that are compatible with that bridge? Someone give me the bridge with 6 bulb and I would like to have more if possible. But I don't know which brand could work with it.

**Comment by sktaylortrash** [comment]
Unfortunately they only ever released two kinds of bulbs for this system the regular A19's and some BR30 spotlights.   I've just been buying batches on ebay like this one - https://www.ebay.ca/itm/TCP-6-Pack-Connected-60w-Equiv-Soft-White-LED-A19-Light-Bulbs-800-Lumens/383065311432?hash=item593078c8c8:g:HPgAAOSw9aJdNyDd
