### ISSUE TITLE
Upstream PR ?

### ISSUE THREAD

**Issue by PartialVolume** [sktaylortrash/TCPLightingWebInterface-MQTT#7]
Just wondering if you had plan to do a PR of this upstream to Bren's code. Seems like a very useful option to have if you don't want to use cloud for voice control (if I've understood it correctly).

**Comment by sktaylortrash** [comment]
When I had spoken to Bren he wasn't interested in combining the code. So that's why I have kept it as a separate project. All the IFTTT stuff still works in this codebase it just adds the MQTT option as well

**Comment by sktaylortrash** [comment]
Closing this as there is no action to be taken
